project_id = "hjtbxxykyyapmizqboxj"

[functions.generate-blog-vision]
verify_jwt = false

[functions.delete-photos]
verify_jwt = false

[functions.cleanup-old-posts]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.admin-update-user-email]
verify_jwt = false

[functions.admin-update-user-password]
verify_jwt = false

[functions.redeem-coupon]
verify_jwt = false
